version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
      - "50051:50051"

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
      - "50052:50052"

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
      - "50053:50053"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
    depends_on:
      - user-service
      - product-service
      - order-service

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mongo_data:
