apiVersion: v1
kind: Secret
metadata:
  name: mongo-urls
type: Opaque
data:
  USER_DB: bW9uZ29kYitzc3J2Oi8vcnAyMzgwMjY0X2RiX3VzZXI6UzcwVnBkdGI5VktzQzIzVEBjbHVzdGVyMC4xZG5kd3cwLm1vbmdvZGJuYXQuZXRuL3VzZXItc2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk= 
  PRODUCT_DB: bW9uZ29kYitzc3J2Oi8vcnAyMzgwMjY0X2RiX3VzZXI6UzcwVnBkdGI5VktzQzIzVEBjbHVzdGVyMC4xZG5kd3cwLm1vbmdvZGJuYXQuZXRuL3Byb2R1Y3Qtc2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  ORDER_DB: bW9uZ29kYitzc3J2Oi8vcnAyMzgwMjY0X2RiX3VzZXI6UzcwVnBkdGI5VktzQzIzVEBjbHVzdGVyMC4xZG5kd3cwLm1vbmdvZGJuYXQuZXRuL29yZGVyLXNlcnZpY2U/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
